import { z } from 'zod';
import { createConnector } from '../packages/connector-sdk/src/builder';
export const pagerdutyConnector = createConnector({ id: 'pagerduty', name: 'PagerDuty', version: '1.0.0', category: 'devops', description: 'Incident management and alerting', color: '#06AC38', icon: 'https://cdn.flowatgenai.com/connectors/pagerduty.svg', tags: ['incidents', 'alerting', 'on-call'], baseUrl: 'https://api.pagerduty.com' })
.withApiKey({ location: 'header', name: 'Authorization', prefix: 'Token token=', fields: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }] })
.withAction('createIncident', { name: 'Create Incident', description: 'Create a new incident', input: z.object({ serviceId: z.string(), title: z.string(), urgency: z.enum(['high', 'low']).optional(), body: z.string().optional() }), output: z.object({ incident: z.object({ id: z.string(), html_url: z.string() }) }), execute: async (i, ctx) => { const r = await ctx.http.post('/incidents', { incident: { type: 'incident', service: { id: i.serviceId, type: 'service_reference' }, title: i.title, urgency: i.urgency, body: i.body ? { type: 'incident_body', details: i.body } : undefined } }); return r.data as Record<string, unknown>; } })
.withAction('getIncident', { name: 'Get Incident', description: 'Get incident details', input: z.object({ incidentId: z.string() }), output: z.object({ incident: z.object({ id: z.string(), status: z.string() }) }), execute: async (i, ctx) => { const r = await ctx.http.get(`/incidents/${i.incidentId}`); return r.data as Record<string, unknown>; } })
.withAction('resolveIncident', { name: 'Resolve Incident', description: 'Resolve an incident', input: z.object({ incidentId: z.string(), resolution: z.string().optional() }), output: z.object({ incident: z.object({ id: z.string(), status: z.string() }) }), execute: async (i, ctx) => { const r = await ctx.http.put(`/incidents/${i.incidentId}`, { incident: { type: 'incident_reference', status: 'resolved', resolution: i.resolution } }); return r.data as Record<string, unknown>; } })
.withWebhookTrigger('incidentTriggered', { name: 'Incident Triggered', description: 'Triggered when an incident is created', output: z.object({ event: z.object({ id: z.string() }) }), signatureHeader: 'x-pagerduty-signature', verifySignature: () => true })
.withRateLimit({ requests: 100, window: 60000, strategy: 'queue' })
.withTestConnection(async (_, ctx) => { try { await ctx.http.get('/users/me'); return { success: true, message: 'Connected' }; } catch { return { success: false, message: 'Failed' }; } })
.build();
export default pagerdutyConnector;
